version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.graalvm.buildtools:native-maven-plugin"
        versions: ["1.1.6"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
